#!/bin/bash -l

# geoblocker-bash-run

# Serves as a proxy to call the -fetch, -apply and -backup scripts with arguments required for each action.
# Intended for easy triggering from the -manage script and from cron jobs.

# all actions:
#     If successful, calls the backup script to create backup of the current iptables state and current ipset.
#     If an error is enountered, classifies it as a temporary or a permanent error.
#     Permanent errors mean that something is fundamentally broken.
#     Temporary errors are transient (for example a download error).
#     For permanent errors, calls the -backup script to restore last known-good ipsets and iptables state.


#### Initial setup

me=$(basename "$0")

# check for root
[[ "$EUID" -ne 0 ]] && {
	err="Error: $me needs to be run as root."
	echo "$err" >&2
	[[ ! "$nolog" ]] && logger "$err"
	exit 1
}

suite_name="geoblocker-bash"
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ -n "$script_dir" ]] && cd "$script_dir" || { err="$me: Error: Couldn't cd into '$script_dir'."; echo "$err" >&2; \
	[[ ! "$nolog" ]] && logger "$err"; exit 1; }

source "$script_dir/${suite_name}-common" || { err="$me: Error: Can't source ${suite_name}-common."; echo "$err" >&2; \
	[[ ! "$nolog" ]] && logger "$err"; exit 1; }

# **NOTE** that some functions and variables are sourced from the *common script


# sanitize arguments
sanitize_args "$@"
# replace arguments with sanitized ones
set -- "${arguments[@]}"


#### USAGE

usage() {
    cat <<EOF

$me
Serves as a proxy to call the -fetch, -apply and -backup scripts with arguments required for each action.

Usage: $me <action> [-c <"country_code [country_code] ... [country_code]">] [-s] [-d] [-h]

Actions:
    add|remove                   : Add or remove country codes to/from geoblocking rules.
    update                       : Fetch ip lists and reactivate them via the *apply script.

Options:
    -c <"country_codes">          : country codes (ISO 3166-1 alpha-2). if passing multiple country codes, use double quotes.

    -s                            : Skip fetching (only run the apply script). For update action only.
    -o                            : No backup: don't create backup of current iptables state before the action.

    -d                            : Debug
    -h                            : This help

EOF
}

#### PARSE ARGUMENTS

# 1st argument should be the requested action
action_run="$1"
shift 1

# check for valid action
case "$action_run" in
	add | remove | update ) ;;
	* ) usage; err1="Error: Unrecognized action: '$action_run'."; err2="Specify action in the 1st argument!"; die "$err1" "$err2" ;;
esac

# process the rest of the arguments
while getopts ":c:osdh" opt; do
	case $opt in
		c) arg_ccodes=$OPTARG;;
		s) skipfetch="true";;
		o) nobackup="true";;
		d) debugmode_args="true";;
		h) usage; exit 0;;
		\?) usage; die "Error: Unknown option: '$OPTARG'." ;;
	esac
done
shift $((OPTIND -1))

[[ -n "$*" ]] && {
	usage
	err1 "Error in arguments. First unrecognized argument: '$1'."
	err2="Note: If specifying multiple country codes, put them in double quotation marks."
	die "$err1" "$err2"
}

echo

# get debugmode variable from either the args or environment variable, depending on what's set
debugmode="${debugmode_args:-$debugmode}"
# set env var to match the result
export debugmode="$debugmode"

# Print script enter message for debug
debugentermsg


#### VARIABLES

# Read current set of countries from the the config file into config_ccodes
config_ccodes="$(getconfig "Countries")" || die "Error: Couldn't read value for Countries from the config file."

if [[ -z "$arg_ccodes" || "$action_run" = "update" ]]; then
	ccodes="$config_ccodes"
else
	ccodes="$arg_ccodes"
fi

# trim single-quotes if any
ccodes="${ccodes//\'}"

# trim extra whitespaces
ccodes="$(awk '{$1=$1};1' <<< "$ccodes")"

ccodes_cnt=$(echo "$ccodes" | wc -w)

# get list_type from the config file
list_type="$(getconfig "ListType")" || die "Error: Couldn't read value for ListType from the config file."

# set global variable
export list_type="$list_type"

#convert to lower case
action_run="${action_run,,}"

# get datadir from the config file
datadir="$(getconfig "Datadir")" || die "Error: Couldn't read value for Datadir from the config file."

knowngood_file="$datadir/iptables_knowngood.bak"
iplist_dir="$datadir/ip_lists"

status_file="$iplist_dir/status"

failed_ccodes_cnt=0


#### CHECKS

missing_deps="$(check_deps "curl|wget" jq iptables-save iptables-restore ipset ${suite_name}-fetch ${suite_name}-apply ${suite_name}-backup)" \
	|| die "Error: missing dependencies: $missing_deps."

# check that the config file exists
[[ ! -f "$conf_file" ]] && die "Config file '$conf_file' doesn't exist! Run the installation script again."

[[ -z "$knowngood_file" ]] && die "Error: Known-good file path can not be empty! Exiting."

[[ -z "$iplist_dir" ]] && die "Error: iplist file path can not be empty! Exiting."

# check for country ccodes
[[ -z "$ccodes" ]] && { err="ccodes variable can not be empty! Exiting."; usage; die "$err"; }

# check for valid action

[[ -z "$action_run" ]] && { usage; die "Specify action!"; }

# translate *run action to *apply action
case "$action_run" in
	add) action_apply="add" ;;
	remove) action_apply="remove" ;;
	update) action_apply="add" ;;
	*) usage; die "Error: unsupported action '$action_run'" ;;
esac

[[ -z "$list_type" ]] && die "\$list_type variable should not be empty! Something is wrong!"

#### MAIN


### Fetch ip lists

if [[ ! "$skipfetch" && "$action_run" != "remove" ]]; then

	# mark all ccodes as failed in the status file before launching *fetch. if *fetch completes successfully, it will reset this
	setstatus "$status_file" "failed_ccodes=$ccodes" || die "Error: Failed to write to status file '$status_file'."

	${suite_name}-fetch -c "$ccodes" -p "$iplist_dir" -s "$status_file"

	# read *fetch results from the status file
	ccodes_to_update="$(getstatus "$status_file" "ccodes_to_update")" || { die "Error: Couldn't read value for 'ccodes_to_update' from status file '$status_file'."; }
	failed_ccodes="$(getstatus "$status_file" "failed_ccodes")" || { die "Error: Couldn't read value for 'failed_ccodes' from status file '$status_file'."; }

	[[ -n "$failed_ccodes" ]] && echolog -err "Failed to fetch and validate subnet lists for countries '$failed_ccodes'."

	failed_ccodes_cnt=$(echo "$failed_ccodes" | wc -w)

	[[ "$failed_ccodes_cnt" -ge "$ccodes_cnt" ]] && die 254 "All fetch attempts failed."

else
	ccodes_to_update="$ccodes"
	debugprint "Skipped fetch because '-s' switch was used"
fi

echo


### Apply ip lists

if [[ -z "$ccodes_to_update" ]]; then
	echolog "Ip lists don't require firewall reconfiguration."
else
	if [[ -z "$nobackup" ]]; then
		# check config coherency vs active ipsets and firewall rules before creating backup
		check_ccodes_coherency; rv=$?
		if [[ $rv -eq 0 ]]; then
			# call the backup script to create a known-good backup of ipsets and iptables state
			${suite_name}-backup create-backup
		else
			echolog -err "Warning: actual $list_type firewall config differs from the config file!"
			echolog -err "Please run the *manage script to restore config coherency!"
			echolog -err "If it's a recurring issue, please consider filing a bug report!"
			[[ -n "$unexpected_ccodes" ]] && echolog -err "Unexpected country codes in the firewall: '$unexpected_ccodes'"
			[[ -n "$missing_ccodes" ]] && echolog -err "Missing country codes in the firewall: '$missing_ccodes'"
			echo
		fi
	else
		debugprint "Skipping backup of current firewall state."
	fi

	${suite_name}-apply "$action_apply" -c "$ccodes_to_update"; rv=$?

#	[[ "$testmode" ]] && rv=1

	if [[ $rv -eq 254 ]]; then
		debugprint "NOTE: *apply exited with error code 254."
		echo
		echolog -err "Error: *apply exited with code '254'. Failed to apply action '$action_apply'."
	elif [[ $rv -gt 0 && $rv -ne 254 ]]; then
		debugprint "NOTE: *apply exited with error code '$rv'."
		echo
		# if fatal errors occur in *apply, attempt to restore last known-good ipsets and iptables state
		# if we're in install, skip this step because there is no backup of ipsets anyway
		[[ ! "$in_install" ]] && ${suite_name}-backup restore; rv="$?"

		# exit with the same exit code as backup-restore operation
		die "$rv"
	else
		echolog "successfully applied action '$action_run' for countries '$ccodes_to_update'."
	fi
fi

if [[ "$failed_ccodes_cnt" -ne 0 ]]; then
	debugprint "failed_ccodes_cnt: $failed_ccodes_cnt"
	rv=254
else
	rv=0
fi

debugexitmsg

unset debugmode
unset list_type

exit "$rv"
