#!/usr/bin/env bash

# geoblocker_bash-backup

# Creates a backup of the current iptables states and current ipsets or restores the above from backup.
# Supported actions: -b (backup), -r (restore)

# 'geoblocker_bash-backup -f <backup_file> -b' :
#     Creates a backup of the current iptables state and current geoblocker-associated ipsets

# 'geoblocker_bash-backup -f backup_file -r' : Used for automatic recovery from fault conditions
#     Restores ipsets and iptables state from backup.
#     If restore from backup fails, assumes a fundamental issue and calls the uninstall script
#     to perform a partial uninstall (removes associated ipsets and iptables rules,
#     restores pre-install policies for INPUT and FORWARD iptables chains,
#     does not remove installed files, config and data).

me=$(basename "$0")
suite_name="geoblocker_bash"
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[ -n "$script_dir" ] && cd "$script_dir" || { echo "Error: Couldn't cd into '$script_dir'."; exit 1; }

source "${suite_name}-common" || { echo "Error: Can't find ${suite_name}-common."; exit 1; }
# **NOTE** that some functions and variables are sourced from the *common script


#### USAGE

usage() {
    cat <<EOF

$me
- Creates a backup of the current iptables states and current ipsets,
- or restores the above from backup
- if restore from backup fails, calls the uninstall script to perform a partial uninstall

    Usage: $me <-b|-r> [-d] [-h]

    Options:
        -b          : action: create backup
        -r          : action: restore from backup

        -d          : Debug
        -h          : This help

EOF
}

#### PARSE ARGUMENTS
while getopts "brdh" opt; do
	case $opt in
		b) act_backup="true";;
		r) act_restore="true";;
		d) debug="-d";;
		h) usage; exit 0;;
		\?) usage; exit 1;;
	esac
done
shift $((OPTIND -1))

echo ""

# Print script enter message for debug
debugentermsg


#### FUNCTIONS

knowngood_failed() {
	err1="$1"; err2="$2"
	echo ""
	echo "$err1" >&2; echo "$err2" >&2
	# print errors to syslog
	[ "$nolog" != "true" ] && { logger -t ${suite_name}-backup "$err1"; logger -t ${suite_name}-backup "$err2"; }
	${suite_name}-uninstall -p
	[ -n "$parent_script" ] && debugprint "\033[1;33mBack to $parent_script...\033[0m"
	exit 1
}

# not needed anymore but leaving it in for now
restart_fail2ban() {
# fail2ban doesn't handle well flushing the INPUT chain then restoring iptables
# this function restarts fail2ban service after these operations in order to work around that issue
	systemctl is-enabled fail2ban &> /dev/null; rv=$?
	if [ $rv -eq 0 ]; then
		echo -n "Restarting fail2ban..." >&2
		systemctl restart fail2ban; rv=$?
		if [ $rv -eq 0 ]; then
			echo "Ok." >&2
		else
			echo "Failed." >&2
		fi
	fi
	echo ""
}

restore_from_file() {
# restores iptables and ipset state from a backup file
	restoretarget="$1"
	restorefile="$2"
	echo "Checking the $restoretarget portion of the backup file..."

	# count lines in the corresponding portion of the backup file
	case "$restoretarget" in
		iptables) line_cnt=$(sed -e '/\[IPSET\].*/Q' "$restorefile" | wc -l) ;;
		ipset) line_cnt=$(sed -n "/create ${suite_name}/,\$p" "$restorefile" | grep "add ${suite_name}" | wc -l) ;;
	esac
	debugprint "$restoretarget lines number in backup: $line_cnt"

	if [ "$line_cnt" -gt 0 ]; then
		echo -n "Restoring $restoretarget state from backup... "

		case "$restoretarget" in
			# reads <$restorefile> from beginning to [IPSET] and pipes the result into iptables-restore
			iptables) sed -e '/\[IPSET\]/Q' "$restorefile" 2>&1 | iptables-restore; rv="${PIPESTATUS[1]}" ;;

			# reads <$restorefile> from "create ${suite_name}" to EOF and pipes the result into "ipset restore"
			ipset) sed -n "/create ${suite_name}/,\$p" "$restorefile" 2>&1 | ipset restore; rv="${PIPESTATUS[1]}" ;;
		esac

		if [ $rv -eq 0 ]; then
			echo "Success."

# not needed anymore
#			if [ "$restoretarget" = "iptables" ]; then restart_fail2ban; fi
			return 0
		else
			echo "Failure."
			err1="Failed to restore $restoretarget known-good state from backup."
		fi
	else
		err1="Error: $restoretarget backup appears to be empty or non-existing."
	fi

	# if we are here then something is seriously broken (unless the script ran in test mode with the -t switch)
	# run the uninstall script with -p switch to restore iptables to pre-install state but leave files in place
	err2="*** Reverting iptables to pre-install state and removing cron jobs ***"

	# if -t switch wasn't specified at launch then it's not a test
	if [ ! "$test" ]; then
		knowngood_failed "$err1" "$err2"
	else
		echo "$err1"
		echo "-t switch was specified, which means we are in test mode. Skipping uninstall."
		echo "WARNING: RECOVERY TEST FAILED AND GEOBLOCKER IS CURRENTLY INACTIVE"

		if [ "$restoretarget" = "iptables" ]; then
# not needed anymore
#			restart_fail2ban
			die 1 -nolog
		fi
	fi
	echo ""; echo ""
}

restoreknowngood() {
# resets iptables policies and rules, destroys all associated ipsets and then initiates restore from file
	restorefile="$1"

	echo ""; echo ""
	msg1="NOTE: Resetting iptables rules for ${suite_name}... "
	echo "$msg1" >&2
	[ "$nolog" != "true" ] && logger -t ${suite_name}-backup  "$msg1"

	echo "Setting INPUT chain policy to ACCEPT... "
	iptables -P INPUT ACCEPT

	# sed looks for rules with the comment which we use to stamp our rules
	# sed executes iptables -D (delete) command on matching rules. execution is promtped by the switch /e (only available in GNU sed)
	iptables-save | sed -r "/INPUT.*comment.*${iptables_comment}/s/-A/iptables -D/e" &>/dev/null; rv=$?
	if [ $rv -ne 0 ]; then
		echo "Failure."
		die "Error removing existing rules with command: iptables-save | sed -r \"/INPUT.*comment.*$iptables_comment/s/-A/iptables -D/e\"."
	else
		echo "Ok."
	fi

	for curr_ipset in $(ipset list -n | grep "$ipset_tag"); do
		echo -n "Destroying ipset \"$curr_ipset\"... "
		ipset destroy "$curr_ipset"; rv=$?
		if [ $rv -ne 0 ]; then
			echo ""
			die "Error destroying ipset \"$curr_ipset\"."
		else
			echo "Ok."
		fi
	done

	msg1="NOTE: Restoring last known-good ipset and iptables from backup... "
	echo "$msg1" >&2
	echo "Backup file: $restorefile"
	echo ""

	restore_from_file "ipset" "$restorefile"
	restore_from_file "iptables" "$restorefile"
}


#### VARIABLES

iptables_comment="$suite_name"
ipset_tag="$suite_name"

# get datadir from the config file
datadir="$(getconfig "Datadir" "$conf_file")"

conf_file_backup="$datadir/${suite_name}.conf.bak"
knowngood_file="$datadir/iptables_knowngood.bak"


#### CHECKS

# check for root
if [ "$EUID" -ne 0 ]; then
	die "This needs to be run as root."
fi

# check that the config file exists
[ ! -f "$conf_file" ] && die "Config file '$conf_file' doesn't exist! Run the installation script again."

# check that conflicting actions were not requested
if [ "$act_backup" ] && [ "$act_restore" ]; then usage; die "Conflicting actions requested: -b and -r can not be used together."; fi

# check that an action was specified
if [ ! "$act_backup" ] && [ ! "$act_restore" ]; then usage; die "Use \"-b\" or \"-r\" to specify action"; fi

# check for knowngood file path
if [ -z "$knowngood_file" ]; then
	die "Error: Could not read the backup file path from config."
fi

# Check for ipset utility
if ! command -v "ipset" &> /dev/null; then
	die "Error: Can not find 'ipset'. Install it with 'apt install ipset' or similar."
fi

# Check for iptables-save utility
if ! command -v "iptables-save" &> /dev/null; then
	die "Error: Can not find 'iptables-save'."
fi

# Check for iptables-restore utility
if ! command -v "iptables-restore" &> /dev/null; then
	die "Error: Can not find 'iptables-restore'."
fi


#### MAIN

if [ "$act_backup" ]; then
### Create backup file for known-good iptables state and save current state to the file

	echo -n "Creating backup of current iptables state... "
	touch "${knowngood_file}.new"

	iptables-save > "${knowngood_file}.new"; rv=$?
	[ "$rv" -ne 0 ] && die "Error creating backup of iptables state with command: \"iptables-save > ${knowngood_file}.new\"."
	echo "Ok."

		# we use the same file for iptables and ipset backup
		# the "[IPSET]" line separates portions of the file
		echo "[IPSET]" >> "${knowngood_file}.new"

	for curr_ipset in $(ipset list -n | grep "$ipset_tag"); do
		echo -n "Creating backup of ipset \"$curr_ipset\"... "
		ipset save "$curr_ipset" >> "${knowngood_file}.new"; rv=$?
		[ "$rv" -ne 0 ] && die "Error creating backup of ipset \"$curr_ipset\"."
		echo "Ok."
	done

	cp "$conf_file" "$conf_file_backup"; rv=$?
	[ "$rv" -ne 0 ] && die "Error creating a backup copy of the config file."

	mv "$knowngood_file.new" "$knowngood_file"; rv=$?
	[ "$rv" -ne 0 ] && die "Error overwriting the backup file."

	echo ""
	echo "Successfully created backup of config, ipsets and iptables rules."
	echo "Backup file: \"$knowngood_file\""
fi

if [ "$act_restore" ]; then
### Restore iptables and ipsets to known-good state from backup file
	restoreknowngood "$knowngood_file"
	msg1="Successfully restored known-good ipset and iptables state from backup."
	echo "$msg1"; echo ""
	[ "$nolog" != "true" ] && logger -t ${suite_name}-backup  "$msg1"
	cp "$conf_file_backup" "$conf_file"; rv=$?
	[ "$rv" -ne 0 ] && die "Error restoring the config file from backup."
fi

debugexitmsg

exit 0
