#!/bin/bash -l

# geoblocker_bash-run

# Runs the geoblocker_bash-fetch script to fetch ip lists from RIPE
# Then runs geoblocker_bash-apply to add/remove/apply the ip lists to iptables
# Config (including countries list) is taken from the config file in /etc/geoblocker_bash/geoblocker_bash.conf

me=$(basename "$0")

#### USAGE

usage() {
    cat <<EOF

Runs the geoblocker_bash-fetch script to fetch ip list from RIPE.
Then runs geoblocker_bash-apply to apply the ip list to iptables.

    Usage: $me -a <update|add|remove> [-c <"tld [tld] ... [tld]">] [-s] [-p] [-d] [-h]

    Options:
        -a <action>     : action to perform: "update", "add" or "remove" associated iptables rules
        -c <"tld/s">    : tld / country codes. if passing multiple country codes, use double quotes
        -s              : Skip fetching (only run the apply script)
        -p              : No Drop: applies the config but skips setting INPUT chain default policy to DROP
                                   (continue to accept all connections)

        -d              : Debug
        -h              : This help

EOF
}

#### PARSE ARGUMENTS

while getopts "a:c:spdh" opt; do
	case $opt in
		a) action=$OPTARG;;
		c) arg_tlds=$OPTARG;;
		s) skipfetch="true";;
		p) nodrop="-p";;
		d) debug="-d";;
		h) usage; exit 0;;
		\?) usage; exit 1;;
	esac
done
shift $((OPTIND -1))


#### FUNCTIONS

die() {
	echo ""
	echo "$@" 1>&2
	echo ""
	logger -t geoblocker_bash-run "$@"
	exit 1
}

get_script_dir () {
	SOURCE=${BASH_SOURCE[0]}
	while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
		DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
		SOURCE=$(readlink "$SOURCE")
		[[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE
		# if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
	done
	DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
	echo "$DIR"
}

getconfig() {
# reads a field named $1 from the config file $2
# outputs the resulting field
# returns 0 if successful, 1 if not
	fieldname="$1"
	configfile="$2"
	read -r field < <(grep "$fieldname=" "$conf_file" | sed 's/.*$fieldname=//'); rv=$?
	if [ -z "$field" ]; then
		echo ""
		rv=$((rv + 1))
	else
		echo "$field"
	fi
	return $rv
}

debugpr() {
# prints a debug message
	[ "$debug" ] && echo "Debug: $@"
}


#### VARIABLES

conf_dir="/etc/geoblocker_bash"
conf_file="${conf_dir}/geoblocker_bash.conf"

# read datadir from the config file
read -r datadir < <(getconfig "Datadir" "$conf_file")
preinstall_policies_file="$datadir/preinstall_policies.bak"
knowngood_file="$datadir/iptables_knowngood.bak"
whitelist_dir="$datadir/ip_lists"
failed_tlds_file="$datadir/FailedTLDs"

if [ -z "$arg_tlds" ] || [ "$action" = "update" ]; then
	# read tlds from the config file
	read -r tlds < <(getconfig "Countries" "$conf_file")
else
	tlds="$arg_tlds"
fi

# get the script path
read -r scriptdir < <(get_script_dir)

echo ""


#### CHECKS

# check for geoblocker_bash-fetch
[ ! $skipfetch ] && if ! command -v geoblocker_bash-fetch &> /dev/null; then
	err="Error: Cannot find \"geoblocker_bash-fetch\". Did you run setup? Exiting."
	die "$err"
fi

# check for geoblocker_bash-apply
if ! command -v geoblocker_bash-apply &> /dev/null; then
	err="Error: Cannot find \"geoblocker_bash-apply\". Did you run setup? Exiting."
	die "$err"
fi

case "$action" in
	add) apply_action="add" ;;
	remove) apply_action="remove" ;;
	update) apply_action="add" ;;
	*) usage; echo "Error: unsupported action \"$action\""; exit 1 ;;
esac

# check for country tlds
if [ -z "$tlds" ]; then
	err="tlds variable can not be empty! Exiting."
	usage
	die "$err"
fi

if [ -z "$knowngood_file" ]; then
	err="Error: Known-good file path can not be empty! Exiting."
	usage
	die "$err"
fi

if [ -z "$whitelist_path" ]; then
	err="Error: Whitelist file path can not be empty! Exiting."
	usage
	die "$err"
fi

# check for root
if [ "$EUID" -ne 0 ]; then
	err="This needs to be run as root."
	die "$err"
fi


#### MAIN

# cd into script directory
# exit in case "cd" fails
cd "$scriptdir" || err="Error: could not change directory to \"$scriptdir\". Exiting."; die "$err"

### Fetch ip lists
errcnt="0"
ok_cnt="0"
failed_tlds=""
ok_tlds=""
if [ ! "$skipfetch" ] && [ "$action" != "remove" ]; then
	for tld in $(echo "${tlds}"); do
		geoblocker_bash-fetch $debug -c "$tld"; rv=$?
		if [ $rv -ne 0 ]; then
			errcnt=$((errcnt + 1)
			failed_tlds="$(echo $failed_tlds) $tld"
			debugpr "Failed to retrieve ip list for country \"$tld\"."
		else
			ok_cnt=$((ok_cnt + 1)
			ok_tlds="$(echo $ok_tlds) $tld"
			debugpr "Successfully retrieved ip list for country \"$tld\"."
		fi
	done

	if [ "$errcnt" -gt 0 ]; then
		logger -t geoblocker_bash-run "Failed to fetch the whitelist for countries\"$failed_tlds\"."
		echo "FailedTLDs=$failed_tlds" > "$failed_tlds_file"
	fi

	if [ "$ok_cnt" -gt 0 ]; then
		logger -t geoblocker_bash-run "Successfully fetched the whitelist for countries\"$ok_tlds\"."
	else
		err="All fetch attempts failed."
		die "$err"
	fi

	tlds="$ok_tlds"
else
	echo "NOTE: Skipped fetching because -s switch was used"
fi


### Apply ip lists

for tld in $(echo "${tlds}"); do
	geoblocker_bash-apply $debug $nodrop -a "$apply_action" -c "$tld"; rv=$?
	if [ $rv -ne 0 ]; then
		echo ""
		# if any errors occur in *apply, exit with a negative return code
		exit -1
	else
		debugpr "Successfully applied the whitelist for country \"$tld\"."
	fi
done

logger -t geoblocker_bash-run "Successfully applied action \"$action\" for countries \"$tlds\"."

echo ""

exit $errcnt
